services:
  mongo:
    image: mongo:7
    container_name: mean_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    networks: [mean_net]

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mean_api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGO_URI: mongodb://admin:admin123@mongo:27017/miapp?authSource=admin
    depends_on: [mongo]
    networks: [mean_net]

  web:
    build:
      context: ./AppFront
      dockerfile: Dockerfile.web
    container_name: mean_web
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    depends_on: [api]
    networks: [mean_net]

volumes:
  mongo_data:

networks:
  mean_net:
